version: '3.8'

services:
  web:
    image: ghcr.io/aiastia/blind-watermark-web/web:main
    ports:
      - "8000:8000"
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
    volumes:
      - temp_data:/app/temp
    restart: unless-stopped

  bot:
    image: ghcr.io/aiastia/blind-watermark-web/bot:main
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:-}
    volumes:
      - temp_data:/app/temp_bot
    restart: unless-stopped
    depends_on:
      - web

volumes:
  temp_data: